In [8]:
# Задание 1 Создайте numpy array с элементами от числа N до 0 
# (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

import numpy as np
a = np.arange(0, 11)
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
# Задание 2 Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

a = np.diag(np.arange(0, 11), k=0)
a[::-1]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [10]:
print(np.trace(a))

55


In [11]:
# Задание 3 Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [7]:
# Задание 4 Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок 
# категорий товаров этим пользователем. Заходит новый пользователь. Найдите самого похожего пользователя. 
# Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])


def cosine( users_stats, next_user_stats ):
    users = np.linalg.norm( next_user_stats )
    new_user = np.linalg.norm( users_stats )
    
    return np.dot( users_stats, next_user_stats ) / (  users * new_user )

list(cosine( users_stats, next_user_stats ))

[0.04688072309384954,
 0.2344036154692477,
 0.09376144618769908,
 0.2344036154692477,
 0.09376144618769908,
 0.0,
 0.0,
 0.14064216928154863,
 0.0,
 0.0]